name: ShippingReports
description: ''
version: 1.1.7
author: sparklearner123@gmail.com
language: python
buildSystem: wheel
pipelines:
  pipelines/Pricing:
    name: Pricing
    description: creates a report summarizing prices, discounts, and shipping status
    author: sparklearner123@gmail.com
    mode: batch
    language: python
    createdAt: '2022-12-08 21:02:35'
    modifiedAt: '2023-03-10 22:22:29'
    datasets:
      inputs:
      - datasets/Shipments
      outputs:
      - datasets/PricingReport
    dependencies: {}
datasets:
  datasets/Shipments:
    name: Shipments
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-08 21:05:07'
    modifiedAt: '2023-03-10 22:20:17'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: Warehouse
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-08 21:05:07'
        modifiedAt: '2022-12-08 21:05:07'
  datasets/report_shipment_prices:
    name: report_shipment_prices
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-08 21:12:16'
    modifiedAt: '2023-03-08 15:13:22'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: Database
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-08 21:12:16'
        modifiedAt: '2022-12-08 21:12:16'
  datasets/Orders_TPCH:
    name: Orders_TPCH
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-02-25 01:28:30'
    modifiedAt: '2023-02-25 01:28:30'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-02-25 01:28:30'
        modifiedAt: '2023-02-25 01:28:30'
  datasets/Customer_TPCH:
    name: Customer_TPCH
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-02-27 20:51:42'
    modifiedAt: '2023-03-06 17:01:45'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-02-27 20:51:42'
        modifiedAt: '2023-02-27 20:51:42'
  datasets/UnshippedOrders:
    name: UnshippedOrders
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-02 21:16:25'
    modifiedAt: '2023-03-03 21:09:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-02 21:16:25'
        modifiedAt: '2023-03-02 21:16:25'
  datasets/UnshippedOrdersEncoded:
    name: UnshippedOrdersEncoded
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-03 21:12:22'
    modifiedAt: '2023-03-03 22:15:00'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-03 21:12:22'
        modifiedAt: '2023-03-03 21:12:22'
  datasets/Unshipped:
    name: Unshipped
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-03 22:17:17'
    modifiedAt: '2023-03-03 22:19:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-03 22:17:17'
        modifiedAt: '2023-03-03 22:17:17'
  datasets/testconfig:
    name: testconfig
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-07 22:10:55'
    modifiedAt: '2023-03-08 14:55:48'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-07 22:10:55'
        modifiedAt: '2023-03-07 22:10:55'
  datasets/PricingReport:
    name: PricingReport
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-08 15:15:42'
    modifiedAt: '2023-03-10 22:20:35'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-08 15:15:42'
        modifiedAt: '2023-03-08 15:15:42'
templates: {}
jobs:
  jobs/PricingReportBatchJob:
    name: PricingReportBatchJob
    description: ''
    fabricUID: 990
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0/2 * * * ? *
    timeout: null
    alerting:
      emails: oncall@acme.com
      onStart: true
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/Pricing
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2022-12-08 21:21:01'
    modifiedAt: '2023-03-10 18:34:34'
    author: sparklearner123@gmail.com
  jobs/PipelineConfiguredJob:
    name: PipelineConfiguredJob
    description: ''
    fabricUID: 990
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/Pricing
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-03-10 19:27:33'
    modifiedAt: '2023-03-10 19:27:54'
    author: sparklearner123@gmail.com
  jobs/ConfiguredPricingJob:
    name: ConfiguredPricingJob
    description: ''
    fabricUID: 990
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/Pricing
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-03-10 22:08:15'
    modifiedAt: '2023-03-10 22:08:43'
    author: sparklearner123@gmail.com
  jobs/ConfiguredJob:
    name: ConfiguredJob
    description: ''
    fabricUID: 990
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/Pricing
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-03-10 22:23:03'
    modifiedAt: '2023-03-10 22:23:29'
    author: sparklearner123@gmail.com
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
