name: ShippingReports
description: ''
version: 0.0.7
author: sparklearner123@gmail.com
language: python
buildSystem: wheel
pipelines:
  pipelines/Pricing:
    name: Pricing
    description: creates a report summarizing prices, discounts, and shipping status
    author: sparklearner123@gmail.com
    mode: batch
    language: python
    createdAt: '2022-12-08 21:02:35'
    modifiedAt: '2023-03-02 21:59:05'
    datasets:
      inputs:
      - datasets/Customer_TPCH
      - datasets/Orders_TPCH
      - datasets/Shipments
      outputs:
      - datasets/UnshippedOrders
      - datasets/report_shipment_prices
    dependencies: {}
datasets:
  datasets/Shipments:
    name: Shipments
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-08 21:05:07'
    modifiedAt: '2022-12-08 21:05:07'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: Warehouse
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-08 21:05:07'
        modifiedAt: '2022-12-08 21:05:07'
  datasets/report_shipment_prices:
    name: report_shipment_prices
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-08 21:12:16'
    modifiedAt: '2022-12-08 21:12:16'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: Database
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-08 21:12:16'
        modifiedAt: '2022-12-08 21:12:16'
  datasets/Orders_TPCH:
    name: Orders_TPCH
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-02-25 01:28:30'
    modifiedAt: '2023-02-25 01:28:30'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-02-25 01:28:30'
        modifiedAt: '2023-02-25 01:28:30'
  datasets/Customer_TPCH:
    name: Customer_TPCH
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-02-27 20:51:42'
    modifiedAt: '2023-02-27 20:51:42'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-02-27 20:51:42'
        modifiedAt: '2023-02-27 20:51:42'
  datasets/UnshippedOrders:
    name: UnshippedOrders
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-02 21:16:25'
    modifiedAt: '2023-03-02 21:57:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-02 21:16:25'
        modifiedAt: '2023-03-02 21:16:25'
templates: {}
jobs:
  jobs/PricingReportBatchJob:
    name: PricingReportBatchJob
    description: ''
    fabricUID: 990
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0/2 * * * ? *
    timeout: null
    alerting:
      emails: oncall@acme.com
      onStart: true
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/Pricing
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2022-12-08 21:21:01'
    modifiedAt: '2022-12-08 21:21:01'
    author: sparklearner123@gmail.com
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
